AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  AppLogLevel:
    Type: String
    Default: INFO
Globals:
  Function:
    Timeout: 10
    LoggingConfig:
      LogFormat: JSON
      ApplicationLogLevel: !Ref AppLogLevel
Resources:
  Synthetics:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      PackageType: Image
      Timeout: 10 # Optional: Adjust timeout as needed
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .

