AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  AppLogLevel:
    Type: String
    Default: INFO
Globals:
  Function:
    Timeout: 10
    LoggingConfig:
      LogFormat: JSON
      ApplicationLogLevel: !Ref AppLogLevel
Resources:
  Synthetics:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Synthetics
      PackageType: Image
      Timeout: 30 # Optional: Adjust lambda timeout as needed
      Policies:
        - Statement:
          - Sid: CloudwatchPutMetricPolicy
            Effect: Allow
            Action:
              - cloudwatch:PutMetricData
            Resource: '*'
      Environment:
        Variables:
          CONCURRENCY: '20'
          TIMEOUT: '10'
          CLOUDWATCH: '1'
      Events:
          Synthetics:
              Type: ScheduleV2
              Properties:
                  Name: lambda-schedumed-synthetics
                  ScheduleExpression: 'cron(0/5 * * * ? *)'
                  ScheduleExpressionTimezone: "Asia/Tokyo"
                  Input: |
                    {
                      "urls": [
                        "https://www.yahoo.co.jp",
                        "https://www.google.com",
                        "https://x.com"
                      ]
                    }
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
