AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  AppLogLevel:
    Type: String
    Default: INFO
Globals:
  Function:
    Timeout: 10
    LoggingConfig:
      LogFormat: JSON
      ApplicationLogLevel: !Ref AppLogLevel
Resources:
  Synthetics:
    Type: 'AWS::Serverless::Function'
    Properties:
      PackageType: Image
      Timeout: 10 # Optional: Adjust timeout as needed
      Policies:
        - Statement:
          - Sid: CloudwatchPutMetricPolicy
            Effect: Allow
            Action:
              - cloudwatch:PutMetricData
            Resource: '*'
      Events:
          Synthetics:
              Type: ScheduleV2
              Properties:
                  ScheduleExpression: 'rate(5 minute)'
                  Input: '{"urls":["https://www.yahoo.co.jp","https://www.google.com","https://twitter.com"],"concurrency":20,"timeout":60,"cloudwatch":true}'
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
